[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x', 'openssl']

[phases.install]
cmds = ['npm ci --prefer-offline --no-audit']

[phases.build]
cmds = [
  'npx prisma generate',
  'npx prisma db push --accept-data-loss',
  'npm run build'
]

[start]
cmd = 'npm start'
