[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x', 'openssl', 'postgresql', 'python39', 'gcc']

[phases.install]
cmds = ['npm ci --prefer-offline --no-audit']

[phases.build]
cmds = [
  'npx prisma generate',
  'npm run build'
]

[start]
cmd = 'bash start.sh'
